#!/bin/zsh
file="$1"
current_time=$(date "+%Y.%m.%d-%H.%M.%S")
java -jar ~/eclipse-workspace/pinyin/target/pinyin-0.0.1-SNAPSHOT.jar -f $file  > anki_$current_time.csv
echo "Wrote CSV file to anki_$current_time.csv"


